
seed: 1234
cudnn_deter: True
device: 'cuda:0'

# Data files
ckpt_dir: "exp/checkpoints/{}"
best_ckpt: "exp/checkpoints/3.pt"

# Model parameters
max_len: 64
input_dim: 7853
output_dim: 5893
hid_dim: 256
encoder_layers: 2
decoder_layers: 2
encoder_heads: 4
decoder_heads: 4
encoder_pf_dim: 128
decoder_pf_dim: 128
encoder_dropout: 0.1
decoder_dropout: 0.1

# Training parameters
hparas:  
  lr: 0.0005
  epoch_num: 100
  log_interval: 10
